language: python
python:
- 3.6
- 3.7
- 3.8
cache:
  pip: true
env:
  jobs:
    - DJANGO_VERSION='Django~=2.2'
install:
- pip install -U pip setuptools
- pip install $DJANGO_VERSION
- pip install .
scripts: echo no-tests
deploy:
  provider: pypi
  server: https://nexus.fool.com/repository/fool-python/
  username: 0RLgWU5S
  password: 6lSoJ2Ic_pSS81YujMXTvuXf1CLhWg_HadlfFN3er3WX
  skip_existing: true
  on:
    tags: true
